### ISSUE TITLE
/api/events/{id}のtagsをnullではなく空配列で返して欲しい。

### ISSUE THREAD

**Issue by KokiKono** [enow-dev/enow#180]
# 概要
<img width="493" alt="2017-09-11 20 17 15" src="https://user-images.githubusercontent.com/20081398/30272209-5b919772-972e-11e7-83a0-042df33a416b.png">

# 目的

# 提案内容

# タスク
- [ ] 

# 概要

# 再現手順

# 原因

# 修正案

**Comment by pei0804** [comment]
あーね

**Comment by pei0804** [comment]
いまからやりまー
