### ISSUE TITLE
スケジュール

### ISSUE THREAD

**Issue by pei0804** [enow-dev/enow#33]
|日付|フロント|サーバー|
|:----|:-------|:--------|
|28|実際にリクエスト投げて画面描画(mock使う) | Datastoreの作成とバッチ処理の作成 |
|29|継続して作業進める| SerachAPIの作成 |
|30| 検索画面の作業開始|検索画面向けのロジック作成 |
|31|検索画面の作業継続| タグ周りの作業？ |
|9/1| 学校なので適当に進める|学校なので適当に進める|
|2| ユーザー認証周りする|ユーザー認証周りする|
|3| 〆作業|〆作業|

上のような感じになりそう

**Comment by KokiKono** [comment]
おけい！
