### ISSUE TITLE
次を読み込み処理とrequest headerの連携

### ISSUE THREAD

**Issue by KokiKono** [enow-dev/enow#91]
# 概要
https://github.com/thlorenz/parse-link-header

# 目的

# 提案内容

# タスク
- [ ] 

# 概要

# 再現手順

# 原因

# 修正案

**Comment by KokiKono** [comment]
サーバー側でレスポンスヘッダにAccess-Control-Allow-Originを追加しないとlinkにアクセスできないみたい。なお、今返って来ているのはcache-control,content-type,expiresの３つ

**Comment by pei0804** [comment]
あーなるほど

**Comment by pei0804** [comment]
対応するわ
